//number data type

let pi = 3.14;
let prime = 29;

console.log(pi, prime);
console.log(typeof pi);
console.log(typeof prime);

//special numeric value
let infi = Infinity;
let negInfi = -Infinity;
let temp = NaN;//notaNumber
temp = NaN +2;
temps = NaN ** 0;
console.log(temp); //any added to it will became NaN
console.log(temps);//any thing power of 0 is "1"


console.log(infi, negInfi);

console.log(typeof infi);
console.log(typeof temp);

console.log(1/0);//this will give Infinity we cannot crash the JS like faitel error or error while debug .
//the other laguage  codes will throws exceptions 

//"sum" variable to save 543 + 245; and print it's type 
let sum = 543 + 245;

console.log(typeof sum);
console.log(sum);